In [1]:
import pandas as pd
import numpy as np

raw_data = pd.read_csv("C:/Users/jsolorzano/Downloads/tweets.csv")

text_data = raw_data[["Tweet"]]

In [4]:
from openai import AzureOpenAI
import os
import json

endpoint = os.getenv("ENDPOINT_URL", "")  
deployment = os.getenv("DEPLOYMENT_NAME", "")  
subscription_key = os.getenv("AZURE_OPENAI_API_KEY", "")  

# Initialize Azure OpenAI Service client with key-based authentication    
cliente = AzureOpenAI(  
    azure_endpoint=endpoint,  
    api_key=subscription_key,  
    api_version="2024-05-01-preview",
)

text_data_list = raw_data["Tweet"].tolist()

emb = cliente.embeddings.create(
    model=deployment,  # Nombre del deployment que configuraste en Azure
    input=text_data_list
)


embeddings = [item.embedding for item in emb.data]
raw_data["embeddings"] = embeddings

In [5]:
import numpy as np
import pandas as pd

# Ejemplo: Suponiendo que raw_data ya tiene embeddings como arrays NumPy
raw_data["embeddings"] = raw_data["embeddings"].apply(lambda x: np.array(x))  # Asegurar que sean arrays

# Expandir los embeddings en columnas separadas
embeddings_expanded = raw_data["embeddings"].apply(pd.Series)

# Renombrar las columnas para que sean más claras
embeddings_expanded.columns = [f"embedding_{i}" for i in range(embeddings_expanded.shape[1])]

# Combinar con el DataFrame original sin la columna de embeddings original
raw_data_expanded = pd.concat([raw_data.drop(columns=["embeddings"]), embeddings_expanded], axis=1)

# Mostrar las primeras filas del nuevo DataFrame


In [6]:
raw_data_expanded.head(10)
raw_data_expanded

Tweet  like  embedding_0  \
0    La disciplina pesa gramos, el arrepentimiento ...     1     0.001488   
1      No esperes motivación, confía en la constancia.     1     0.009733   
2    Un día a la vez, un entrenamiento a la vez, un...     1     0.012360   
3     Tu único rival es la versión de ti que se rinde.     1    -0.010997   
4    El progreso es silencioso, pero los resultados...     1     0.005367   
..                                                 ...   ...          ...   
185       La vida es corta, explora tanto como puedas.     1     0.001420   
186              Un buen viaje te cambia para siempre.     0     0.007040   
187  No hay mejor sensación que perderse en un luga...     1     0.026036   
188     Un buen compañero de viaje hace la diferencia.     0     0.026766   
189  Las mejores experiencias no tienen precio, tie...     0    -0.009563   

     embedding_1  embedding_2  embedding_3  embedding_4  embedding_5  \
0       0.008207    -0.005979    -0.012738     0.028107    -0.001243   
1       0.000356    -0.016154     0.011625     0.002420     0.033623   
2       0.010357    -0.005567    -0.011176    -0.022214     0.000363   
3       0.005716    -0.003125     0.018590     0.027522    -0.002066   
4       0.019420    -0.017578     0.013661    -0.015104     0.004532   
..           ...          ...          ...          ...          ...   
185     0.007706    -0.007530    -0.025015    -0.003248     0.032913   
186     0.022054     0.003156     0.000540    -0.005767     0.063529   
187     0.040750     0.009493    -0.020334     0.022214     0.028692   
188     0.019759     0.004700    -0.033510    -0.005635     0.039991   
189     0.013651    -0.010362     0.011184     0.002309     0.033076   

     embedding_6  embedding_7  ...  embedding_3062  embedding_3063  \
0      -0.004574     0.001315  ...       -0.002069        0.009064   
1      -0.009122     0.030733  ...        0.006585        0.011995   
2      -0.013889     0.038038  ...        0.018427       -0.001216   
3       0.014904     0.009553  ...       -0.016931        0.023050   
4       0.005597     0.024450  ...       -0.012198       -0.007209   
..           ...          ...  ...             ...             ...   
185    -0.008217    -0.002827  ...        0.004015        0.016039   
186    -0.036879     0.017231  ...        0.011135        0.013757   
187    -0.048311     0.002109  ...        0.007275       -0.013130   
188    -0.018579     0.012615  ...        0.027317        0.002832   
189    -0.036779    -0.000967  ...        0.001412       -0.006124   

     embedding_3064  embedding_3065  embedding_3066  embedding_3067  \
0         -0.003939        0.009786        0.010572        0.018218   
1          0.012465        0.002793        0.023907        0.017187   
2          0.009695        0.015232        0.010639        0.008800   
3          0.005194       -0.007931        0.006444        0.023848   
4         -0.003903       -0.000280        0.007511        0.024271   
..              ...             ...             ...             ...   
185       -0.014807       -0.010780        0.004532        0.023783   
186       -0.008254        0.018493       -0.014005        0.043115   
187       -0.019292        0.012211       -0.010647        0.055668   
188       -0.012438        0.019353        0.008443        0.020337   
189        0.005155        0.013272       -0.003925        0.042691   

     embedding_3068  embedding_3069  embedding_3070  embedding_3071  
0          0.004358       -0.030015        0.007343        0.004400  
1         -0.009968       -0.010332       -0.025564       -0.014333  
2          0.002828        0.005467        0.026291        0.000645  
3         -0.003717        0.010689       -0.019130       -0.005950  
4         -0.005398        0.001042        0.002063       -0.008734  
..              ...             ...             ...             ...  
185        0.005181       -0.013849       -0.003779        0.010208  
186  

In [22]:
#import xgboost
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(raw_data_expanded.drop(columns=["Tweet", "like"]), raw_data_expanded["like"], test_size=0.5, random_state=42)


In [ ]:
import mlflow
import mlflow.sklearn
import xgboost as xgb
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# Cargar dataset de ejemplo
from sklearn.datasets import make_classification


# Iniciar MLflow
mlflow.set_experiment("Comparación de Modelos ML")

def train_xgboost():
    """Entrena un modelo XGBoost y lo registra en MLflow"""
    with mlflow.start_run(run_name="XGBoost Model"):
        model = xgb.XGBClassifier(
            objective="binary:logistic",
            eval_metric="logloss",
            use_label_encoder=False,
            max_depth=6,
            learning_rate=0.1,
            n_estimators=300,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
        )
        
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        print(acc)
        print(classification_report(y_test, preds))

        # Registrar en MLflow
        mlflow.log_params(model.get_params())
        mlflow.log_metric("accuracy", acc)
        mlflow.sklearn.log_model(model, "xgboost_model")

        print(f"XGBoost Accuracy: {acc:.4f}")

def train_random_forest():
    """Entrena un modelo RandomForest y lo registra en MLflow"""
    with mlflow.start_run(run_name="RandomForest Model"):
        model = RandomForestClassifier(n_estimators=200, max_depth=6, random_state=42)
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        print(acc)
        print(classification_report(y_test, preds))

        # Registrar en MLflow
        mlflow.log_params(model.get_params())
        mlflow.log_metric("accuracy", acc)
        mlflow.sklearn.log_model(model, "random_forest_model")

        print(f"RandomForest Accuracy: {acc:.4f}")

def train_neural_network():
    """Entrena una Red Neuronal con Keras y la registra en MLflow"""
    with mlflow.start_run(run_name="Neural Network Model"):
        model = keras.Sequential([
            layers.Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
            layers.Dense(32, activation="relu"),
            layers.Dense(1, activation="sigmoid"),
        ])
        
        model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
        
        history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=32, verbose=1)
        
        preds = (model.predict(X_test) > 0.5).astype(int)
        acc = accuracy_score(y_test, preds)
        print(acc)
        print(classification_report(y_test, preds))

        # Registrar en MLflow
        mlflow.log_params({"epochs": 10, "batch_size": 32})
        mlflow.log_metric("accuracy", acc)
        mlflow.keras.log_model(model, "neural_network_model")

        print(f"Neural Network Accuracy: {acc:.4f}")

# Entrenar los modelos
train_xgboost()
train_random_forest()
train_neural_network()


C:\Users\jsolorzano\Desktop\joaquin\tweets_liking_prediction\.venv\Lib\site-packages\xgboost\core.py:158: UserWarning: [23:30:00] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


0.9368421052631579
              precision    recall  f1-score   support

           0       0.88      0.97      0.92        36
           1       0.98      0.92      0.95        59

    accuracy                           0.94        95
   macro avg       0.93      0.94      0.93        95
weighted avg       0.94      0.94      0.94        95



2025/02/22 23:30:11 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2025/02/22 23:30:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


XGBoost Accuracy: 0.9368
0.8842105263157894
              precision    recall  f1-score   support

           0       0.78      0.97      0.86        36
           1       0.98      0.83      0.90        59

    accuracy                           0.88        95
   macro avg       0.88      0.90      0.88        95
weighted avg       0.90      0.88      0.89        95



2025/02/22 23:30:16 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2025/02/22 23:30:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.


RandomForest Accuracy: 0.8842
Epoch 1/10


C:\Users\jsolorzano\Desktop\joaquin\tweets_liking_prediction\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/3 ━━━━━━━━━━━━━━━━━━━━ 4s 2s/step - accuracy: 0.4375 - loss: 0.6955

In [15]:
model = xgb.XGBClassifier(
            objective="binary:logistic",
            eval_metric="logloss",
            use_label_encoder=False,
            max_depth=6,
            learning_rate=0.1,
            n_estimators=300,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
        )
        
model.fit(X_train, y_train)
preds = model.predict(X_test)
accuracy_score(y_test, preds)

C:\Users\jsolorzano\Desktop\joaquin\tweets_liking_prediction\.venv\Lib\site-packages\xgboost\core.py:158: UserWarning: [23:23:57] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


0.9368421052631579

In [16]:
text = "Ir al gym es lo mejor que te puede pasar en la vida"
def get_model_inference(text):
  emb = cliente.embeddings.create(
    model=deployment,
    input=text
  )

  embedding = emb.data[0].embedding
  pred = model.predict([embedding])
  return pred

get_model_inference(text)

array([1])

In [17]:
text = "Td diste cuenta de lo que paso?"
def get_model_inference(text):
  emb = cliente.embeddings.create(
    model=deployment,
    input=text
  )

  embedding = emb.data[0].embedding
  pred = model.predict([embedding])
  return pred

get_model_inference(text)

array([0])

In [18]:
text = "La industria del desarrollo de software esta por cambiar por completo"
def get_model_inference(text):
  emb = cliente.embeddings.create(
    model=deployment,
    input=text
  )

  embedding = emb.data[0].embedding
  pred = model.predict([embedding])
  return pred

get_model_inference(text)

array([1])